name: update

on:
  schedule:
    - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build the project
      run: cargo build --release

    - name: Run your code
      run: cargo run --release

    - name: Commit and push changes
      run: |
        git config --local user.email "blue.neutron460@slmail.me"
        git config --local user.name "musdx"
        git add .
        git commit -m "Automated update"
        git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
